// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSx5eRoGvCif8IsWNSLQ_L6KqWhrIDNzk',
    appId: '1:730361736768:web:30b3dc5d7aef39908279a5',
    messagingSenderId: '730361736768',
    projectId: 'talkest-94a3b',
    authDomain: 'talkest-94a3b.firebaseapp.com',
    storageBucket: 'talkest-94a3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe-GIjxTzFdYGDQ5biFPrvOeKNzKFlQe4',
    appId: '1:730361736768:android:05d200b0fe34a0968279a5',
    messagingSenderId: '730361736768',
    projectId: 'talkest-94a3b',
    storageBucket: 'talkest-94a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ur0etrnvKZX7l_iXFw7tC6XdbBImhEI',
    appId: '1:730361736768:ios:cf3c6e21c46dafc88279a5',
    messagingSenderId: '730361736768',
    projectId: 'talkest-94a3b',
    storageBucket: 'talkest-94a3b.firebasestorage.app',
    iosClientId: '730361736768-8b86e3i7sqpkaav82pbv9n7vtb6ukd1p.apps.googleusercontent.com',
    iosBundleId: 'com.khip.talkest',
  );
}
